version: '2'

services:
  django:
    environment:
      - DEBUG=False

  rqworker:
    environment:
      - DEBUG=False

  vue:
    command: ./production_server.sh

  nginx:
    environment:
      - BUFFERING=on
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /cert:/cert
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
