version: '2'

services:

  redis:
    restart: always
    image: redis

  rqworker:
    build: backend
    image: dab/django
    restart: always
    command: ./rqworker_reload.sh
    links:
      - redis
      - ice
    depends_on:
      - redis
      - ice
    volumes:
      - ./backend:/code

  django:
    image: dab/django
    restart: always
    command: gunicorn website.wsgi:application -b :8082 --reload
    links:
      - redis
      - rqworker
      - ice
    depends_on:
      - redis
      - rqworker
      - ice
    volumes:
      - ./backend:/code



  vue:
    restart: always
    build: frontend
    command: npm run dev
    volumes:
      - ./frontend:/code
      - /code/node_modules
  
  ice:
    build: ice
    image: jbei/ice:latest
    restart: always
    links:
      - postgres
    ports:
      - '127.0.0.1:9999:8080'
    volumes:
      - index:/var/lib/ice/lucene
      - localdata:/usr/local/tomcat/data
    expose:
      - 8080

  postgres:
    image: library/postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: ice
      POSTGRES_PASSWORD: icepass
      POSTGRES_USER: iceuser
    volumes:
      - postgres:/var/lib/postgresql/data
      - /backups:/backups
    logging:
      driver: 'json-file'
      options:
        max-size: 1m
        max-file: '5'
    expose:
      - '5432'
  
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    links:
      - vue
      - django
      - ice
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx_dab:/var/log/nginx

volumes:
  postgres: {}
  index: {}
  localdata: {}