version: '2'

services:
  django:
    environment:
      - DEBUG=False

  rqworker:
    environment:
      - DEBUG=False

  vue:
    command: ./production_server.sh

  nginx:
    environment:
      - BUFFERING=on
    build: ../EGFNginx
    links:
      - "vue:vue"
      - django
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
    volumes:
      - /srv/nginx/conf:/etc/nginx/conf.d
      - /srv/nginx/www:/var/www
      - /srv/nginx/log:/var/log/nginx
      - /srv/nginx/sys:/sys
      - /cert:/cert
